package cz.czmendelu.studymate.localization

data class AppStrings(
    val subjects: String,
    val settings: String,

    val createNewSubject: String,
    val editSubject: String,
    val subjectName: String,
    val create: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val confirmDeleteTitle: String,
    val confirmDeleteSubjectMessage: String,
    val confirmDeleteQuestionMessage: String,
    val confirmDeleteTestMessage: String,
    val tapToOpen: String,
    val subjectListEmpty: String,

    val addQuestion: String,
    val editQuestion: String,
    val saveChanges: String,
    val hasImage: String,
    val importQuestionsAi: String,
    val aiImportUnavailableTitle: String,
    val aiImportUnavailableMessage: String,
    val aiImportTitle: String,
    val aiImportDescription: String,
    val sourceText: String,
    val importQuestions: String,
    val importingQuestions: String,
    val createTest: String,
    val tests: String,
    val questions: String,
    val results: String,
    val score: String,

    val question: String,
    val answer: String,
    val questionType: String,
    val saveQuestion: String,
    val addImageFromGallery: String,
    val selectedImage: String,
    val removeImage: String,
    val correctYesNoAnswer: String,

    val testName: String,
    val testType: String,
    val numberOfQuestions: String,
    val timedTest: String,
    val createTestButton: String,
    val finishTest: String,

    val language: String,
    val darkMode: String,
    val enabled: String,
    val disabled: String,
    val about: String,
    val version: String,
    val build: String,
    val madeForStudents: String,
    val slogan: String,

    val yes: String,
    val no: String,
    val correct: String,
    val incorrect: String,
    val questionCounter: String,
    val tapCardToShowAnswer: String,
    val tapCardToShowQuestion: String,
    val loadingTest: String,
    val proposedAnswer: String,
    val yourAnswer: String,
    val correctAnswer: String,
    val answerDetails: String,
    val notAnswered: String,
    val confirm: String,
    val noImageSelected: String,
    val noImageOptionsAvailable: String,
    val selected: String,
    val image: String,

    val studySessionComplete: String,
    val reviewedFlashcards: String,
    val studyAgain: String,
    val backToSubject: String
)

fun appStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> AppStrings(
            subjects = "Subjects",
            settings = "Settings",

            createNewSubject = "Create new subject",
            editSubject = "Edit subject",
            subjectName = "Subject name",
            create = "Create",
            save = "Save",
            cancel = "Cancel",
            delete = "Delete",
            confirmDeleteTitle = "Delete item?",
            confirmDeleteSubjectMessage = "Do you really want to delete this subject?",
            confirmDeleteQuestionMessage = "Do you really want to delete this question?",
            confirmDeleteTestMessage = "Do you really want to delete this test?",
            tapToOpen = "Tap to open",
            subjectListEmpty = "Subject list is empty",

            addQuestion = "Add Question",
            editQuestion = "Edit Question",
            saveChanges = "Save changes",
            hasImage = "Has image",
            importQuestionsAi = "Import Questions (AI)",
            aiImportUnavailableTitle = "AI import",
            aiImportUnavailableMessage = "This feature is prepared as a prototype, but it is not connected to an external AI service in this version.",
            aiImportTitle = "Import questions with AI",
            aiImportDescription = "Paste your notes or study text. AI will generate flashcard questions and answers from it.",
            sourceText = "Source text",
            importQuestions = "Import questions",
            importingQuestions = "Importing questions...",
            createTest = "Create Test",
            tests = "Tests",
            questions = "Questions",
            results = "Results",
            score = "Score",

            question = "Question",
            answer = "Answer",
            questionType = "Question type",
            saveQuestion = "Save question",
            addImageFromGallery = "Add image from gallery",
            selectedImage = "Selected image:",
            removeImage = "Remove image",
            correctYesNoAnswer = "Correct Yes/No answer",

            testName = "Test name",
            testType = "Test type",
            numberOfQuestions = "Number of questions",
            timedTest = "Timed test",
            createTestButton = "Create test",
            finishTest = "Finish Test",

            language = "Language",
            darkMode = "Dark Mode",
            enabled = "Enabled",
            disabled = "Disabled",
            about = "About",
            version = "Version",
            build = "Build",
            madeForStudents = "Made for students",
            slogan = "Learn smarter, not harder",

            yes = "Yes",
            no = "No",
            correct = "Correct",
            incorrect = "Incorrect",
            questionCounter = "Question",
            tapCardToShowAnswer = "Tap card to show answer",
            tapCardToShowQuestion = "Tap card to show question again",
            loadingTest = "Loading test...",
            proposedAnswer = "Proposed answer:",
            yourAnswer = "Your answer",
            correctAnswer = "Correct answer",
            answerDetails = "Answer details",
            notAnswered = "Not answered",
            confirm = "Confirm",
            noImageSelected = "No image selected",
            noImageOptionsAvailable = "No image options available",
            selected = "Selected",
            image = "Image",

            studySessionComplete = "Study Session Complete!",
            reviewedFlashcards = "You reviewed flashcards",
            studyAgain = "Study Again",
            backToSubject = "Back to Subject"
        )

        AppLanguage.CZECH -> AppStrings(
            subjects = "Předměty",
            settings = "Nastavení",

            createNewSubject = "Vytvořit nový předmět",
            editSubject = "Upravit předmět",
            subjectName = "Název předmětu",
            create = "Vytvořit",
            save = "Uložit",
            cancel = "Zrušit",
            delete = "Smazat",
            confirmDeleteTitle = "Smazat položku?",
            confirmDeleteSubjectMessage = "Opravdu chceš smazat tento předmět?",
            confirmDeleteQuestionMessage = "Opravdu chceš smazat tuto otázku?",
            confirmDeleteTestMessage = "Opravdu chceš smazat tento test?",
            tapToOpen = "Klepni pro otevření",
            subjectListEmpty = "Seznam predmetu je prazdny",

            addQuestion = "Přidat otázku",
            editQuestion = "Upravit otázku",
            saveChanges = "Uložit změny",
            hasImage = "Obsahuje obrázek",
            importQuestionsAi = "Import otázek (AI)",
            aiImportUnavailableTitle = "AI import",
            aiImportUnavailableMessage = "Tato funkce je připravena jako prototyp, ale v této verzi není napojená na externí AI službu.",
            aiImportTitle = "Import otázek pomocí AI",
            aiImportDescription = "Vlož poznámky nebo učební text. AI z něj vytvoří otázky a odpovědi typu kartička.",
            sourceText = "Zdrojový text",
            importQuestions = "Importovat otázky",
            importingQuestions = "Importuji otázky...",
            createTest = "Vytvořit test",
            tests = "Testy",
            questions = "Otázky",
            results = "Výsledky",
            score = "Skóre",

            question = "Otázka",
            answer = "Odpověď",
            questionType = "Typ otázky",
            saveQuestion = "Uložit otázku",
            addImageFromGallery = "Přidat obrázek z galerie",
            selectedImage = "Vybraný obrázek:",
            removeImage = "Odebrat obrázek",
            correctYesNoAnswer = "Správná odpověď Ano/Ne",

            testName = "Název testu",
            testType = "Typ testu",
            numberOfQuestions = "Počet otázek",
            timedTest = "Časovaný test",
            createTestButton = "Vytvořit test",
            finishTest = "Dokončit test",

            language = "Jazyk",
            darkMode = "Tmavý režim",
            enabled = "Zapnuto",
            disabled = "Vypnuto",
            about = "O aplikaci",
            version = "Verze",
            build = "Build",
            madeForStudents = "Vytvořeno pro studenty",
            slogan = "Uč se chytřeji, ne složitěji",

            yes = "Ano",
            no = "Ne",
            correct = "Správně",
            incorrect = "Špatně",
            questionCounter = "Otázka",
            tapCardToShowAnswer = "Klepni na kartu pro zobrazení odpovědi",
            tapCardToShowQuestion = "Klepni na kartu pro zobrazení otázky",
            loadingTest = "Načítám test...",
            proposedAnswer = "Navržená odpověď:",
            yourAnswer = "Tvoje odpověď",
            correctAnswer = "Správná odpověď",
            answerDetails = "Detail odpovědí",
            notAnswered = "Nezodpovězeno",
            confirm = "Potvrdit",
            noImageSelected = "Nebyl vybrán obrázek",
            noImageOptionsAvailable = "Nejsou dostupné obrázkové možnosti",
            selected = "Vybráno",
            image = "Obrázek",

            studySessionComplete = "Učení dokončeno!",
            reviewedFlashcards = "Prošel jsi kartičky",
            studyAgain = "Procvičit znovu",
            backToSubject = "Zpět na předmět"
        )
    }
}
